# K8s-DaaS E2E Integration Test Environment
version: '3.8'

services:
  # Nautilus Control - K8s Master with Real Sui Integration
  nautilus-control:
    build:
      context: ./nautilus-release
      dockerfile: Dockerfile
    container_name: nautilus-control
    ports:
      - "6444:6443"    # K3s API Server
      - "8081:8080"    # HTTP API
    environment:
      - CONTRACT_ADDRESS=0x7cec09084d43c2b8b9dd217b3bf69316b04e924e455b80b8813873e5c52cadd6
      - PRIVATE_KEY=suiprivkey1qqd74wmst3u3ar3kenngevpnayu0n4kvdklu9ses22p7pfev7x53yugm7aw
      - SUI_RPC_URL=https://fullnode.testnet.sui.io:443
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - nautilus-data:/var/lib/rancher/k3s
      - nautilus-config:/etc/rancher/k3s
    networks:
      - k3s-daas-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

  # K3s Worker Node - Receives commands from Nautilus Control
  worker-node-1:
    build:
      context: ./worker-release
      dockerfile: Dockerfile.simple
    container_name: worker-node-1
    environment:
      - MASTER_URL=https://nautilus-control:6443
      - NODE_TOKEN=${NODE_TOKEN:-waiting-for-master}
      - SEAL_TOKEN=seal_token_worker_123
      - NODE_ID=worker-node-001
    depends_on:
      - nautilus-control
    networks:
      - k3s-daas-network
    restart: unless-stopped
    volumes:
      - worker1-data:/var/lib/rancher/k3s
    privileged: true

volumes:
  nautilus-data:
    driver: local
  nautilus-config:
    driver: local
  worker1-data:
    driver: local

networks:
  k3s-daas-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16