# Walrus Simulator Configuration for DaaS Testing
[aggregator]
listen_address = "0.0.0.0:31415"
aggregator_address = "0.0.0.0:31416"
data_path = "/data"
max_blob_size = "100MB"
max_concurrent_requests = 100

[storage]
# Storage configuration for simulator
storage_type = "memory"  # Use memory for fast testing
max_storage_size = "10GB"
replication_factor = 3
shard_size = "1MB"

[network]
# Simplified network for local testing
node_id = "walrus-simulator-001"
seed_nodes = []
discovery_enabled = false
bootstrap_nodes = []

[sui_integration]
# Sui blockchain integration
sui_rpc_url = "http://sui-node:9000"
sui_private_key_path = "/config/sui_private_key"
sui_package_id = "0x1234567890abcdef1234567890abcdef12345678"
gas_budget = 1000000

[blob_store]
# Blob storage configuration
max_blob_size = "100MB"
compression_enabled = true
encryption_enabled = false  # Disabled for testing
deduplication_enabled = true

[attestation]
# Attestation service configuration
enable_attestation = true
attestation_service_url = "http://nautilus-attestation:8090"
verification_timeout = "30s"

[api]
# API configuration
enable_cors = true
cors_origins = ["*"]
rate_limit_requests_per_minute = 1000
max_request_size = "10MB"

[monitoring]
# Monitoring and metrics
metrics_enabled = true
metrics_port = 9091
health_check_interval = "10s"
log_level = "info"

[simulator]
# Simulator-specific settings
simulate_network_delays = false
simulate_failures = false
failure_rate = 0.0
network_delay_ms = 0

# Storage node simulation
storage_nodes = [
    { id = "storage-1", address = "127.0.0.1:8081", capacity = "1GB" },
    { id = "storage-2", address = "127.0.0.1:8082", capacity = "1GB" },
    { id = "storage-3", address = "127.0.0.1:8083", capacity = "1GB" }
]

[security]
# Security settings for testing
enable_tls = false
enable_authentication = false
trusted_certificates = []

[performance]
# Performance tuning for testing
worker_threads = 4
async_operations_limit = 1000
connection_pool_size = 50
request_timeout = "30s"