# K3s Server Configuration for DaaS Testing
---
# Cluster configuration
cluster-init: true
token: "daas-test-token-12345"
write-kubeconfig-mode: "0666"
kubeconfig-output: "/output/kubeconfig.yaml"

# Network configuration
cluster-cidr: "10.42.0.0/16"
service-cidr: "10.43.0.0/16"
cluster-dns: "10.43.0.10"
cluster-domain: "cluster.local"

# API server configuration
bind-address: "0.0.0.0"
https-listen-port: 6443
advertise-address: "k3s-server"

# Disable unnecessary components for testing
disable:
  - traefik
  - servicelb
  - metrics-server

# Enable necessary features for DaaS
kube-apiserver-arg:
  - "enable-admission-plugins=NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook"
  - "feature-gates=DynamicAuditing=true"
  - "audit-log-path=/var/log/audit.log"
  - "audit-log-maxage=30"
  - "audit-log-maxbackup=3"
  - "audit-log-maxsize=100"

kube-controller-manager-arg:
  - "feature-gates=DynamicAuditing=true"
  - "node-monitor-period=5s"
  - "node-monitor-grace-period=20s"

kubelet-arg:
  - "feature-gates=DynamicAuditing=true"
  - "max-pods=100"
  - "node-status-update-frequency=5s"

# Etcd configuration for testing
etcd-arg:
  - "listen-metrics-urls=http://0.0.0.0:2381"
  - "experimental-initial-corrupt-check=true"

# TLS configuration
tls-san:
  - "k3s-server"
  - "127.0.0.1"
  - "localhost"
  - "172.20.0.2"

# Data directory
data-dir: "/var/lib/rancher/k3s"

# Logging
log-level: "info"

# Node configuration
node-name: "daas-control-plane"
node-label:
  - "node-role.kubernetes.io/control-plane=true"
  - "daas.io/blockchain-enabled=true"
  - "daas.io/testing=true"

node-taint:
  - "node-role.kubernetes.io/control-plane:NoSchedule"